### ISSUE TITLE
ws运行久了就会报错

### ISSUE THREAD

**Issue by fish8848-chen** [yudiandemingzi/spring-boot-netty-websocket-huobi#2]
时间久了，经常会报这样的错，然后就一直报这个错，请问有遇到过吗，然后是否有解决的办法

[ERROR] 2019-11-15 23:10:03 [nioEventLoopGroup-34-1] i.r.c.n.s.h.HuoBiProWebSocketClient - webSocketClient start error.
java.lang.IllegalStateException: executor not accepting a task
at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60)
at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
at java.lang.Thread.run(Thread.java:748)
[ERROR] 2019-10-15 22:00:01 [nioEventLoopGroup-231-1] i.r.c.n.s.h.HuoBiProWebSocketClient - webSocketClient start error.
java.nio.channels.ClosedChannelException: null
at io.netty.channel.nio.AbstractNioChannel.doClose()(Unknown Source)

**Comment by lcxiaoma** [comment]
exceptionCaught 异常会断开 业务自己处理异常就行不要抛出
channelInactive 连接断开 没必要start 因为有定时器定时重连
HuoBiProWebSocketClientHandler
@Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        logger.warn("websocket client disconnected.");
        //client.start();

    }
